server:
  port: 8002

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.atguigu.springcloud.dao.**
  mapper-locations: classpath:mybatis/mapper/**/*.xml

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clouddb02
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: microservicecloud-dept

eureka:
  client:
    service-url:
      defaultZone:  http://eureka7001.com:7001/euraka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservicecloud-8002
    prefer-ip-address: true

info:
  app.com: atguigu-microservicecloud
  company: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$